version: "3.9"

services:
    just-shop:
        build: .
        container_name: justShop
        volumes:
            - .:/home/node/app
        ports:
            - 3022:3022
            - 3099:3099
        restart: unless-stopped
        command: bash -c "npm run generate-mock && npm run dev & npm run start:mock"
